<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>OldReloadSystem</AssemblyName>
    <RootNamespace>OldReloadSystem</RootNamespace>
    <Version>4.9.1</Version>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.364" />
  </ItemGroup>
</Project>
